### PR TITLE
feat: add support for Django 5.0 and 5.1

### LINKED ISSUE #428: Django 5 redefined get_queryset in ChangeList
Django 5 redefined get_queryset in ChangeListto to include fecets in filters.

class VersionChangeList should be defined as:

class VersionChangeList(ChangeList):
...
-    def get_queryset(self, request):
+   def get_queryset(self, request, exclude_parameters=None):
...
-       queryset = super().get_queryset(request)
+      queryset = super().get_queryset(request, exclude_parameters)
..

BR
Borut

### PR DESCRIPTION
**Pull request by fsbraun**
## Description

Fixes #428 by adding the optional parameter `exlude_parameters` to the `VersionedChangeList.get_queryset` method. IF provided it will be passed to the `super().get_queryset` method, if not, it will be omitted (to work with Django 4.2).

## Related resources

* #428 
* #...

## Checklist

* [x] I have opened this pull request against ``master``
* [ ] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on 
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Review by vinitkumar — APPROVED** [review]

**Review by marksweb — COMMENTED** [review]
Are these test failures in the current codebase - I don't see anything here to start invalidating form data

**Comment by fsbraun** [comment]
@marksweb That's interesting. I only updated the changlog. Must be something that changed in develop-4 during the last week; since the merge of f3803cbbc684581ac14bd466c00c0419c8fa3f0f.

**Comment by fsbraun** [comment]
I can only assume it's https://github.com/django-cms/django-cms/pull/8041 which added the missing x frame options to the ChangePage form, and for some reason it stops the change form in the test to validate.

**Comment by fsbraun** [comment]
I would like to double-check that this solves https://github.com/django-cms/django-cms/issues/8044.

**Comment by fsbraun** [comment]
OK, it turns out, https://github.com/django-cms/django-cms/issues/8044 needs an additional fix in the core. This is ready to be merged.

**Pull request merged**
