### PR TITLE
feat: Django 4.2, Django CMS 4.1.0rc2 compatibility, and version locking

### PR DESCRIPTION
**Pull request by fsbraun**
## Description

This PR adds tests for Django 4.2 and mixins for django CMS' `GrouperModelAdmin` class (new in 4.2rc2). It includes the version locking functionality. Version locking is activated by setting `DJANGOCMS_VERSIONING_LOCK_VERSIONS = True` in the project settings.

Documentation has been updated and tests have been added. 

To stay DRY and avoid code repetition, the `djangocms_versioning.admin` module has been slightly refactored. `ExtendedListDisplayMixin` encapsulates the extension of the change list view of versioned objects using django CMS 4's new config feature. Both versioned grouper admins and versioned content admins inherit it.

Djangocms Versioning now supports both versioned grouper model admins and versioned content model admins. The latter are backwards compatible.

## Related resources

* Fixed a bug where the edit button was not grayed-out if the user did not have edit rights
* adds ruff as linter (see also #329)
* https://github.com/FidelityInternational/djangocms-version-locking

## Checklist

* [x] I have opened this pull request against ``master``
* [x] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on 
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Comment by marksweb** [comment]
Ok so my first thing here was to try to install this to see it in action but it's broken version locking. I'll see if I can look into that today and continue with just looking at the code;

```
  File "/Users/mwalker/Sites/consoles/.env/lib/python3.9/site-packages/cms/app_registration.py", line 93, in autodiscover_cms_configs
    app_config.cms_extension = extension()
  File "/Users/mwalker/Sites/consoles/.env/src/djangocms-version-locking/djangocms_version_locking/cms_config.py", line 10, in __init__
    from .monkeypatch import admin as monkeypatch_admin  # noqa: F401
  File "/Users/mwalker/Sites/consoles/.env/src/djangocms-version-locking/djangocms_version_locking/monkeypatch/admin.py", line 148, in <module>
    admin.VersionAdmin.get_state_actions = get_state_actions(admin.VersionAdmin.get_state_actions)
AttributeError: type object 'VersionAdmin' has no attribute 'get_state_actions'
```

**Comment by fsbraun** [comment]
Just added ruff as linter link in #329

**Review by marksweb — APPROVED** [review]
LGTM

**Review by marksweb — APPROVED** [review]
LGTM

**Pull request merged**
